# your domain
domain: sirenzhuanshu.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - ./config/config.yaml
  # use web file
  - https://sirenzhuanshu.herokuapp.com/config.yaml
